name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.board }} ${{ matrix.framework_opts }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        framework:
          - "{type:esp-idf,version:recommended}"
          - "{type:arduino,version:recommended}"
        board:
          - esp32-c3-devkitm-1
          - wt32-eth01
          - esp32-s3-devkitc-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: framework="${{matrix.framework}}" board=${{matrix.board}} envsubst < test/config.yaml.template > test/config.yaml
      - name: Compile
        uses: esphome/build-action@v6
        id: esphome-build
        with:
          yaml-file: test/config.yaml
